export const MAX_SEARCH_RESULTS = 50;
export const VERSION_ID_RANDOM_START = 2;
export const VERSION_ID_RANDOM_END = 9;
export const VERSION_ID_RANDOM_LENGTH = 36;
export const VARIATIONS_COUNT = 3;
export const PROMPT_READY_THRESHOLD = 100;
export const DEBOUNCE_DELAY = 300; // milliseconds
export const MAX_FEATURES_DISPLAY = 3;
export const IDEATION_TEMPERATURE = 0.8;
export const GAME_IDEA_FEATURES_DISPLAY_LIMIT = 5;
export const PAGE_SIZE = 12;
export const WALLET_ADDRESS_PREFIX_LENGTH = 6;
export const WALLET_ADDRESS_SUFFIX_LENGTH = 4;
export const MAX_TAGS_DISPLAY = 3;
export const SANITIZED_TITLE_MAX_LENGTH = 100;

// Blockchain Constants
export const GAME_MARKETPLACE_ADDRESS = "0xDb0E0812bBf50eC0Ffe434b634cC4a0503edCfaa"; // Latest deployment
export const PYTH_CONTRACT_ADDRESS = "0x4305FB66699C3B2702D4d05CF36551390A4c69C6"; // Sepolia testnet
export const IPFS_UPLOAD_TIMEOUT_MS = 60_000;
export const BYTES_PER_MEGABYTE = 1_048_576;
export const MAX_HTML_SIZE_MB = 50;
export const MAX_HTML_SIZE_BYTES = MAX_HTML_SIZE_MB * BYTES_PER_MEGABYTE;
export const PINATA_API_URL = "https://api.pinata.cloud/pinning/pinFileToIPFS";
export const HTTP_STATUS_UNAUTHORIZED = 401;
export const HTTP_STATUS_FORBIDDEN = 403;
export const HTTP_STATUS_TOO_MANY_REQUESTS = 429;
export const HTTP_STATUS_PAYLOAD_TOO_LARGE = 413;
export const MAX_FILENAME_LENGTH = 100;
export const POPULAR_FORK_THRESHOLD = 5;
export const MIN_SELL_PRICE = 0.1;
